# Generated by Django 3.2 on 2023-05-17 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogDuplicate',
        ),
    ]
