# Generated by Django 3.2 on 2023-05-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_delete_blogduplicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='total_comments',
            field=models.IntegerField(default=0),
        ),
    ]
