# Generated by Django 3.2 on 2023-05-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_remove_blog_total_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='total_comments',
            field=models.IntegerField(default=0),
        ),
    ]
