# Generated by Django 3.2 on 2023-05-22 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0005_blog_total_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='total_comments',
        ),
    ]
