# Generated by Django 4.1.3 on 2023-02-13 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note_api', '0002_alter_notemodel_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notemodel',
            options={'ordering': ['id']},
        ),
    ]
