# Generated by Django 3.2 on 2023-03-05 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
